services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: movie_app
        restart: unless-stopped
#        command: sleep infinity # for installing initial dependencies
        depends_on:
            - db
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_DATABASE: movie_db
            DB_USERNAME: root
            DB_PASSWORD: root
            REDIS_HOST: redis
        networks:
            - movie-net

    db:
        image: mysql:8.0
        container_name: movie_db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: movie_db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - movie-net

    redis:
        image: redis:alpine
        container_name: movie_redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - movie-net

    meilisearch:
        image: getmeili/meilisearch:latest
        container_name: meilisearch
        restart: unless-stopped
        ports:
            - "7700:7700"
        environment:
            - MEILI_NO_ANALYTICS=true
            - MEILI_ENV=development
            - MEILI_MASTER_KEY=9Nar66wxd!l^
        volumes:
            - ./docker/meilisearch:/meili_data
        networks:
            - movie-net

networks:
    movie-net:
        driver: bridge

volumes:
    db-data:
        driver: local
